### PR TITLE
Viscous fix

### PR DESCRIPTION
**Pull request by wilfonba**
Includes 1 fluids viscous in 1, 2, and 3D. Should pass on both CPUs and GPUs.

### CODE REVIEW

**Comment by wilfonba** [comment]
Has golden file errors I need to look into apparently.

**Comment by henryleberre** [comment]
@wilfonba You added new test cases but not their golden files!

**Comment by sbryngelson** [comment]
final review is to make sure that the results here match those from pre-viscous refactor

**Comment by wilfonba** [comment]
@sbryngelson I have verified that the golden files I generated pass on MFC V1.4.2 by copying the relevant golden files into the tests directory, adding the tests to the toolchain in this older version, and running the tests without generating new golden files. All tests pass on CPUs and GPUs.

**Review by sbryngelson — APPROVED** [review]

**Pull request merged**
