### PR TITLE
output_partial_domain for post-processing

### PR DESCRIPTION
**Pull request by ChrisZYJ**
## Description

Adds an option to output only part of the domain during post-processing.

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Scope

- [x] This PR comprises a set of related changes with a common goal

## How Has This Been Tested?

- [x] Works as expected when post-processed using Matlab binary reader.
- [x] Passes the original tests with post-processing enabled (with -a)

## Checklist

- [x] I have added comments for the new code
- [x] I added Doxygen docstrings to the new code
- [x] I have made corresponding changes to the documentation (`docs/`)
- [ ] I have added regression tests to the test suite so that people can verify in the future that the feature is behaving as expected
- [ ] I have added example cases in `examples/` that demonstrate my new feature performing as expected.
They run to completion and demonstrate "interesting physics"
- [x] I ran `./mfc.sh format` before committing my code
- [x] New and existing tests pass locally with my changes, including with GPU capability enabled (both NVIDIA hardware with NVHPC compilers and AMD hardware with CRAY compilers) and disabled
- [x] This PR does not introduce any repeated code (it follows the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle)
- [x] I cannot think of a way to condense this code and reduce any introduced additional line count

### CODE REVIEW

**Comment by sbryngelson** [comment]
@ChrisZYJ thanks this appears very useful! I'm curious if this works for a couple different scenarios (have you verified):
* Serial vs serial output
* Format == 1 and 2
* Stretched grids

**Comment by ChrisZYJ** [comment]
It works with stretched grids and both serial and parallel outputs. However, it only works for format == 2 (binary) and not format == 1 (silo). The silo format requires more careful data handling, so perhaps that could be completed in another PR. 

I've documented the scenarios where it doesn't work yet in the documentation and added prohibitions in the checkers.

**Comment by sbryngelson** [comment]
@ChrisZYJ thanks this makes sense. May I ask how you are handling your binary output files? Matlab/Python or into Visit/Paraview? I think this would be useful to either document or perhaps even put a helper script in the `misc/` directory for others.

**Comment by ChrisZYJ** [comment]
I've been doing it in Matlab using the `f_binary_reader.m` function, which is already in the `/misc` directory. I could document it and add my wrapper function to `/misc` later if needed.

**Review by sbryngelson — APPROVED** [review]

**Comment by sbryngelson** [comment]
Thanks @ChrisZYJ. I find using the binary files rather annoying. If we had a more broad way of doing it (and could suggest to the user when and how to do it) that would be useful.

I'm glad to merge the PR but we have two big PRs that are very near merging that I don't want to disrupt. Hopefully can merge this in a couple days.

**Comment by ChrisZYJ** [comment]
Yeah, I also find binary files quite cumbersome to work with. While I'm not sure what a broader way to handle them would be, I can add some documentation and helper scripts in another PR if you find those helpful.

I'm in no hurry to merge. This PR should be quite independent from everything else, and I could easily merge it into them later if needed.

**Comment by sbryngelson** [comment]
> Yeah, I also find binary files quite cumbersome to work with. While I'm not sure what a broader way to handle them would be, I can add some documentation and helper scripts in another PR if you find those helpful.
> 
> I'm in no hurry to merge. This PR should be quite independent from everything else, and I could easily merge it into them later if needed.

That would be very useful indeed. I hope to merge this soon but don't want to risk messing up these larger long-standing PRs right now.

**Pull request merged**
