### PR TITLE
Fix hypoelastic instability

### LINKED ISSUE #771: Instability in Hypoelastic Simulations
### Description

Commit 10b2209 (#727) introduces instability in some hypoelastic simulations compared to previous commit 108805c7.

### Test Case

- Simulation: Simple acoustic wave propagation with sound waves from left focused at a centered stone

- Case file: [case_hypo.txt](https://github.com/user-attachments/files/18234216/case_hypo.txt)

#### Step 300 of the simulation (with commit 10b2209):
image

#### Comparison with the previous commit 108805c7 (top:108805c7 ; bottom:10b2209):
https://github.com/user-attachments/assets/3b05a2a1-08b2-4e0c-ac97-44c6df4f97ae

### Environment & Configuration
- Ubuntu 22.04.4 LTS
- GNU 11.4.0
- Using CPU with both debug enabled and disabled

### PR DESCRIPTION
**Pull request by ChrisZYJ**
## Description

Fixes #771 by reverting the hypoelasticity changes from #727
Adds a test case to prevent similar issues in the future
Also regenerates the hypoelasticity-related test that was generated during #727

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### Scope

- [x] This PR comprises a set of related changes with a common goal

## How Has This Been Tested?

A new test case has been added that covers a scenario similar to #771 and is more comprehensive than existing tests.

The test was generated using commit 108805c7 (before #727), fails after the changes in #727, and passes after the changes in this PR.

### CODE REVIEW

**Comment by sbryngelson** [comment]
@ChrisZYJ I understand why you want to do this. Part of the merged PR #727 was to set the 'groundwork' for pending PR #767 on hyperelasticity and RMT. So, I'm hesitant to merge this because it could mess up the work in #767. Can you work with @mrodrig6 to find a reasonable solution to everything and both PRs?

**Comment by ChrisZYJ** [comment]
@sbryngelson Thanks for raising this! I’ve double-checked, and #767 doesn’t touch m_hypoelastic.fpp, so reverting the hypoelasticity changes shouldn’t conflict with the hyperelasticity/RMT updates. By fixing the stability issue now and adding a test to catch similar regressions, I think #767 would have a better 'groundwork'.

@mrodrig6 Could you please confirm there’s no hidden overlap we’re missing? Thanks!

**Comment by mrodrig6** [comment]
> @sbryngelson Thanks for raising this! I’ve double-checked, and #767 doesn’t touch m_hypoelastic.fpp, so reverting the hypoelasticity changes shouldn’t conflict with the hyperelasticity/RMT updates. By fixing the stability issue now and adding a test to catch similar regressions, I think #767 would have a better 'groundwork'.
> 
> @mrodrig6 Could you please confirm there’s no hidden overlap we’re missing? Thanks!

Yes, that is correct. This does not overlap with the hyperelasticity/RMT updates.

**Comment by ChrisZYJ** [comment]
@mrodrig6 Thank you very much for clarifying! The issue was completely resolved by reverting only m_hypoelastic, likely due to finite-difference stencils in m_helpers.

I agree that grid-stretching is an important feature to keep. May I know if you plan to address the stability issue while preserving grid-stretching in your ongoing commit #767? If so, I suggest merging this #773 first, as its test suites provide correct reference results for easier debugging. You can maintain the existing m_hypoelastic code in #767, and the tests will pass once the issue is fixed.

**Comment by ChrisZYJ** [comment]
I'm not too familiar with the new FD stencil implementations, but I can look into them!

**Review by sbryngelson — APPROVED** [review]

**Pull request merged**
