### PR TITLE
Remove grid stretch parameters from simulation inputs

### PR DESCRIPTION
**Pull request by haochey**
## Description

This PR removes the grid stretch parameters `xyz_{ab}` from the simulation input parameters in `case_dicts.py`.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### Scope

- [x] This PR comprises a set of related changes with a common goal

## How Has This Been Tested?

It builds successfully on my local MacOS. Simulations with stretched grid are not crashing.

* What computers and compilers did you use to test this: MacOS 12.2.1

### CODE REVIEW

**Comment by sbryngelson** [comment]
are you sure simulation doesn't need grid stretching parameters? it's easy to check... I recommend just changing to notation so we don't repeat letters

**Comment by haochey** [comment]
> are you sure simulation doesn't need grid stretching parameters? it's easy to check... I recommend just changing to (IBM) notation so we don't repeat letters

Hi Spencer, I just made a couple tests for IB touching DBs on stretched girds. All the configurations are the same as the test listed in [PR#407](https://github.com/MFlowCode/MFC/pull/407) except for the stretching configuration: 

```
    'stretch_x'                : 'T',
    'a_x'                          : 7,
    'x_a'                          : 0.5*x1,
    'x_b'                          : 1.5*x1,  
    'stretch_y'                : 'T',
    'a_y'                          : 3,
    'y_a'                          : 0.9*x2,
    'y_b'                          : 1.1*x2, 
```

https://github.com/MFlowCode/MFC/assets/98496194/40cbfc1a-b0ca-4f24-8299-c6fc2501a939

 It looks fine to me. The current simulation stage is not using any stretching parameters and the domain sizes are the only additional parameters it needs for IBM.

**Comment by sbryngelson** [comment]
@haochey, thank you - this seems fine to me, though I'm a little confused about the whole situation. @lee-hyeoksu said you added `{xyz}_{ab}` to the case parameter input file for the domain boundary treatment. What are those parameters used for? 

If they are used for something related to IBs, you presumably cannot use both those _and_ domain stretching simultaneously (you would have to pick one or the other). Right?

**Comment by haochey** [comment]
@sbryngelson Thanks for the message.  `xyz_{ab}` are not used for IBs. I believe they are just used in the pre_process stage. 

When I try to add `xyz_{domain%beg}` and `xyz_{domain%end}`, I mistakenly added `xyz_{ab}` to the simulation inputs in `case_dicts.py` as @lee-hyeoksu mentioned. 

Therefore, simply deleting them from the `case_dicts.py` will fix @lee-hyeoksu's issue and won't affect the domain boundary treatment.

**Comment by sbryngelson** [comment]
got it. thanks @haochey. can you sync your fork/branch with master so it runs benchmarking properly and then i can merge

**Comment by haochey** [comment]
It looks like my fork/branch has already synchronized with master. I am not sure why the benchmarking is not running properly.

**Comment by sbryngelson** [comment]
I see - I am re-running them.

**Pull request merged**
