### PR TITLE
Edited m_reimann_solvers.fpp

### PR DESCRIPTION
**Pull request by KrishnaSr71**
I checked with the CI, and everything seems to be working. I condensed 88 lines, but I'm thinking I can condense about 40-50 more, because there's still a lot of duplicate code with maybe one variable name different.

Also, I think I pull-requested my ci.yml file. Is it possible for you to ignore that? I couldn't figure out how to just PR the m_riemann_solvers.fpp file.

Thanks!

### CODE REVIEW

**Review by henryleberre — CHANGES_REQUESTED** [review]
Welcome, @KrishnaSr71 to MFC! Your first commit has hash `91d199255357fbe06564a493844b703e850b1b25`. Thus, you can
```console
$ git reset --soft 91d199255357fbe06564a493844b703e850b1b25~1
```
to un-commit all of your changes, reverting to the commit prior to your first (using `~1` meaning the commit prior), while keeping your aggregate changes staged (but not committed). If you run `git status` you will see them as such. `git log` will show HEAD pointing to an upstream commit.

To discard your modifications to `.github/workflows/ci.yml`, you can unstage it:
```console
$ git restore --staged .github/workflows/ci.yml
```

Now, only `src/simulation/m_riemann_solvers.fpp` is staged. You can
```console
$ git commit
$ git push -f
```

to (force-)update your `master` branch to only contain a single commit that contains all of your changes to `src/simulation/m_riemann_solvers.fpp`. This will make your intermediate commits disappear.

**Comment by sbryngelson** [comment]
@KrishnaSr71 please add back the the self-hosted runners at the bottom of the CI to see if it passes on GPUs.

**Comment by sbryngelson** [comment]
@KrishnaSr71 GPU face failed -- I would look into that. The Intel cases are failing but this is expected at the moment.

**Comment by KrishnaSr71** [comment]
> @KrishnaSr71 GPU face failed -- I would look into that. The Intel cases are failing but this is expected at the moment.

Got it, thanks. Should I close the PR for now?

**Comment by KrishnaSr71** [comment]
Got it.

**Pull request closed without merging**
