### PR TITLE
Links Changed & Deleting defaults.yaml reference

### PR DESCRIPTION
**Pull request by anshgupta1234**
Addresses #121. @henryleberre One thing I did delete in this PR was a reference to a `defaults.yaml` file that I couldn't find anywhere. Is this outdated or should I restore it somehow?

The main change is just editing relative links to absolute links because although the relative links work on GitHub, they don't work on the Github Pages site.

### CODE REVIEW

**Review by henryleberre — APPROVED** [review]
lgtm!

**Comment by henryleberre** [comment]
@anshgupta1234 Good find, I thought I had removed all references to defaults.yml but I missed this one. It was a file that contained all the default values for the arguments you give to mfc.sh. It was never used by anyone and required a fair amount of code to handle so I removed it.

**Comment by anshgupta1234** [comment]
Cool! Actually @henryleberre in toolchain/templates, the script files are still referencing some `mfc.user.yaml` files. Might want to take a look at that.

**Comment by henryleberre** [comment]
... @anshgupta1234, you can remove those two. This file had a quite a few names. One can use the power of `grep`:

```console
$ grep -E -i '\.y(a*)ml' -R . --exclude-dir=build
```

**Comment by henryleberre** [comment]
@anshgupta1234 The macOS workflow sometimes encounters an MPI error when launching a job. I haven't looked too much into it. I reran both the Ubuntu and macOS workflows.

**Comment by sbryngelson** [comment]
> @anshgupta1234 The macOS workflow sometimes encounters an MPI error when launching a job. I haven't looked too much into it. I reran both the Ubuntu and macOS workflows.

I've lost the thread here. How did MPI errors and documentation fixes come into the same issue?

**Comment by henryleberre** [comment]
@sbryngelson This has nothing to do with this PR specifically. The macOS CI workflow sporadically fails when trying to create an MPI process. The error changes but this time, it was:
```console
$ mpirun -np 1 /Users/runner/work/MFC/MFC/build/install/bin/pre_process
  
  --------------------------------------------------------------------------
  A call to mkdir was unable to create the desired directory:
  
    Directory: 
/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/ompi.Mac-[167](https://github.com/MFlowCode/MFC/actions/runs/4452313282/jobs/7819850929#step:6:168)9093159652.501/pid.
43523
    Error:     Invalid argument
  
  Please check to ensure you have adequate permissions to perform
  the desired operation.
  --------------------------------------------------------------------------
  [Mac-1679093159652.local:43523] [[5[185](https://github.com/MFlowCode/MFC/actions/runs/4452313282/jobs/7819850929#step:6:186)1,0],0] ORTE_ERROR_LOG: Error in file 
util/session_dir.c at line 107
  [Mac-1679093159652.local:43523] [[51851,0],0] ORTE_ERROR_LOG: Error in file 
util/session_dir.c at line 346
  --------------------------------------------------------------------------
  It looks like orte_init failed for some reason; your parallel process is
  likely to abort.  There are many reasons that a parallel process can
  fail during orte_init; some of which are due to configuration or
  environment problems.  This failure appears to be an internal failure;
  here's some additional information (which may only be relevant to an
  Open MPI developer):
  
    orte_session_dir failed
    --> Returned value Error (-1) instead of ORTE_SUCCESS
  --------------------------------------------------------------------------
  
  
  Error: Failed to execute command "['mpirun', '-np', 1, 
  '/Users/runner/work/MFC/MFC/build/install/bin/pre_process']".
```

**Comment by sbryngelson** [comment]
Interesting. Not really sure what to make of that.

**Pull request merged**
