### PR TITLE
Mock PR to test benchmarking

### PR DESCRIPTION
**Pull request by wilfonba**
This is a mock PR that checks the benchmarking PR. It does the following:

- Adds a 60 second delay to pre_process for the hypo_hll case
- Adds a print statement to the 5eq_rk3_weno3_hllc case file to cause failure in input generation
- Calls s_mpi_abort in simulation for the viscous_weno5_sgb_mono case
- Allows the IBM case to run to completion

### CODE REVIEW

**Review by sbryngelson — APPROVED** [review]

**Comment by wilfonba** [comment]
I would expect all of the test suites to fail on the first bubbles case since I added an MPI_Abort if bubbles = T. I expected the benchmarks to handle this though since it runs the 4 cases independently. Looking at the CI it appears that neither benchmark actually got a node and ran at all. It could be the case that I needed to introduce a seg fault rather than an MPI_Abort, but I'll have to see what happens when the benchmarks actually run to know.

**Comment by sbryngelson** [comment]
Please sync this branch with master

**Comment by sbryngelson** [comment]
I'd like to see this check get to the point where it gets to point where it actually prints benchmark results (presumably with the aforementioned failures).

**Comment by sbryngelson** [comment]
The only thing I really want to be checked now is if the benchmark cases run on Delta/non-Phoenix computers.

**Comment by wilfonba** [comment]
I'll do a run on delta

**Comment by sbryngelson** [comment]
I just did. Check the issue for the latest at #396

**Comment by sbryngelson** [comment]
this can be closed due to #497 thanks @ChrisZYJ

**Pull request closed without merging**
