### PR TITLE
Adding Hypoelasticity

### PR DESCRIPTION
**Pull request by js-spratt**
Adding hypoelastic modeling to code. This version introduces 6 simple CI tests (2 for 1D, 2D and 3D) for hypoelasticity. More will be added in the future, as well as specific examples of the hypoelastic code. Before generating golden files for these tests, the hypoelastic model implementation has been compared to exact solutions in 1D and 2D, and to experimental results in 3D.

### CODE REVIEW

**Review by henryleberre — APPROVED** [review]

**Comment by sbryngelson** [comment]
@js-spratt Please move all hypoelastic-related calls to a separate module, perhaps `m_hypoelastic.f90`?

**Comment by js-spratt** [comment]
@sbryngelson Ok, I can move things such as the RHS source term calculation to a separate file. However, in many instances the hypoelastic code in a simple modification of an existing routine. In that case, similarly to what is done with the bubble code, should those calls be left in place?

**Comment by sbryngelson** [comment]
> @sbryngelson Ok, I can move things such as the RHS source term calculation to a separate file. However, in many instances the hypoelastic code in a simple modification of an existing routine. In that case, similarly to what is done with the bubble code, should those calls be left in place?

Correct. I mean lines like this that you added should be moved:
```
            ! RHS additions for hypoelasticity
            call nvtxStartRange("RHS_Hypoelasticity")

            if (hypoelasticity) then

                if (id == 1) then
                    ! calculate velocity gradients + rho_K and G_K
                    ! TODO: re-organize these loops one by one for GPU efficiency if possible?
!$acc parallel loop collapse(3) gang vector default(present)
                    do q = 0, p
                        do l = 0, n
                            do k = 0, m
                                du_dx(k, l, q) = &
                                    (q_prim_qp%vf(momxb)%sf(k - 2, l, q) &
                                     - 8d0*q_prim_qp%vf(momxb)%sf(k - 1, l, q) &
                                     + 8d0*q_prim_qp%vf(momxb)%sf(k + 1, l, q) &
                                     - q_prim_qp%vf(momxb)%sf(k + 2, l, q)) &
                                    !                                    / (12d0*(x_cc(k+1) - x_cc(k) ))
                                    /(12d0*dx(k))
                            end do
                        end do
                    end do

                    ! 2D
                    if (n > 0) then
!$acc parallel loop collapse(3) gang vector default(present)
                        do q = 0, p
                            do l = 0, n
                                do k = 0, m
                                    du_dy(k, l, q) = &
                                        (q_prim_qp%vf(momxb)%sf(k, l - 2, q) &
                                         - 8d0*q_prim_qp%vf(momxb)%sf(k, l - 1, q) &
                                         + 8d0*q_prim_qp%vf(momxb)%sf(k, l + 1, q) &
                                         - q_prim_qp%vf(momxb)%sf(k, l + 2, q)) &
                                        !                                        / (12d0*(y_cc(l+1) - y_cc(l) ))
                                        /(12d0*dy(l))
                                    dv_dx(k, l, q) = &
                                        (q_prim_qp%vf(momxb + 1)%sf(k - 2, l, q) &
                                         - 8d0*q_prim_qp%vf(momxb + 1)%sf(k - 1, l, q) &
                                         + 8d0*q_prim_qp%vf(momxb + 1)%sf(k + 1, l, q) &
                                         - q_prim_qp%vf(momxb + 1)%sf(k + 2, l, q)) &
                                        !                                        / (12d0*(x_cc(k+1) - x_cc(k) ))
                                        /(12d0*dx(k))
                                    dv_dy(k, l, q) = &
                                        (q_prim_qp%vf(momxb + 1)%sf(k, l - 2, q) &
                                         - 8d0*q_prim_qp%vf(momxb + 1)%sf(k, l - 1, q) &
                                         + 8d0*q_prim_qp%vf(momxb + 1)%sf(k, l + 1, q) &
                                         - q_prim_qp%vf(momxb + 1)%sf(k, l + 2, q)) &
                                        !                                        / (12d0*(y_cc(l+1) - y_cc(l) ))
                                        /(12d0*dy(l))
                                end do
                            end do
                        end do

                        ! 3D
                        if (p > 0) then
!$acc parallel loop collapse(3) gang vector default(present)
                            do q = 0, p
                                do l = 0, n
                                    do k = 0, m
                                        du_dz(k, l, q) = &
                                            (q_prim_qp%vf(momxb)%sf(k, l, q - 2) &
                                             - 8d0*q_prim_qp%vf(momxb)%sf(k, l, q - 1) &
                                             + 8d0*q_prim_qp%vf(momxb)%sf(k, l, q + 1) &
                                             - q_prim_qp%vf(momxb)%sf(k, l, q + 2)) &
                                            !                                            / (12d0*(z_cc(q+1) - z_cc(q) ))
                                            /(12d0*dz(q))
                                        dv_dz(k, l, q) = &
                                            (q_prim_qp%vf(momxb + 1)%sf(k, l, q - 2) &
                                             - 8d0*q_prim_qp%vf(momxb + 1)%sf(k, l, q - 1) &
                                             + 8d0*q_prim_qp%vf(momxb + 1)%sf(k, l, q + 1) &
                                             - q_prim_qp%vf(momxb + 1)%sf(k, l, q + 2)) &
                                            !                                            / (12d0*(z_cc(q+1) - z_cc(q) ))
                                            /(12d0*dz(q))
                                        dw_dx(k, l, q) = &
                                            (q_prim_qp%vf(momxe)%sf(k - 2, l, q) &
                                             - 8d0*q_prim_qp%vf(momxe)%sf(k - 1, l, q) &
                                             + 8d0*q_prim_qp%vf(momxe)%sf(k + 1, l, q) &
                                             - q_prim_qp%vf(momxe)%sf(k + 2, l, q)) &
                                            !                                            / (12d0*(x_cc(k+1) - x_cc(k) ))
                                            /(12d0*dx(k))
                                        dw_dy(k, l, q) = &
                                            (q_prim_qp%vf(momxe)%sf(k, l - 2, q) &
                                             - 8d0*q_prim_qp%vf(momxe)%sf(k, l - 1, q) &
                                             + 8d0*q_prim_qp%vf(momxe)%sf(k, l + 1, q) &
                                             - q_prim_qp%vf(momxe)%sf(k, l + 2, q)) &
                                            !                                            / (12d0*(y_cc(l+1) - y_cc(l) ))
                                            /(12d0*dy(l))
                                        dw_dz(k, l, q) = &
                                            (q_prim_qp%vf(momxe)%sf(k, l, q - 2) &
                                             - 8d0*q_prim_qp%vf(momxe)%sf(k, l, q - 1) &
                                             + 8d0*q_prim_qp%vf(momxe)%sf(k, l, q + 1) &
                                             - q_prim_qp%vf(momxe)%sf(k, l, q + 2)) &
                                            !                                            / (12d0*(z_cc(q+1) - z_cc(q) ))
                                            /(12d0*dz(q))
                                    end do
                                end do
                            end do
                        end if
                    end if

!$acc parallel loop collapse(3) gang vector default(present)
                    do q = 0, p
                        do l = 0, n
                            do k = 0, m
                                rho_K = 0d0; G_K = 0d0
                                do i = 1, num_fluids
                                    rho_K = rho_K + q_prim_qp%vf(i)%sf(k, l, q) !alpha_rho_K(1)
                                    G_K = G_K + q_prim_qp%vf(advxb - 1 + i)%sf(k, l, q)*Gs(i)  !alpha_K(1) * Gs(1)
                                end do
                                rho_K_field(k, l, q) = rho_K
                                G_K_field(k, l, q) = G_K
                                !TODO: take this out if not needed
                                if (G_K < 1000) then
                                    G_K_field(k, l, q) = 0
                                end if
                            end do
                        end do
                    end do

                    ! apply rhs source term to elastic stress equation
!$acc parallel loop collapse(3) gang vector default(present)
                    do q = 0, p
                        do l = 0, n
                            do k = 0, m
                                rhs_vf(strxb)%sf(k, l, q) = &
                                    rhs_vf(strxb)%sf(k, l, q) + rho_K_field(k, l, q)* &
                                    ((4d0*G_K_field(k, l, q)/3d0) + &
                                     q_prim_qp%vf(strxb)%sf(k, l, q))* &
                                    du_dx(k, l, q)
                            end do
                        end do
                    end do

                elseif (id == 2) then

!$acc parallel loop collapse(3) gang vector default(present)
                    do q = 0, p
                        do l = 0, n
                            do k = 0, m
                                rhs_vf(strxb)%sf(k, l, q) = rhs_vf(strxb)%sf(k, l, q) + rho_K_field(k, l, q)* &
                                                            (q_prim_qp%vf(strxb + 1)%sf(k, l, q)*du_dy(k, l, q) + &
                                                             q_prim_qp%vf(strxb + 1)%sf(k, l, q)*du_dy(k, l, q) - &
                                                             q_prim_qp%vf(strxb)%sf(k, l, q)*dv_dy(k, l, q) - &
                                                             2d0*G_K_field(k, l, q)*(1d0/3d0)*dv_dy(k, l, q))

                                rhs_vf(strxb + 1)%sf(k, l, q) = rhs_vf(strxb + 1)%sf(k, l, q) + rho_K_field(k, l, q)* &
                                                                (q_prim_qp%vf(strxb + 1)%sf(k, l, q)*du_dx(k, l, q) + &
                                                                 q_prim_qp%vf(strxb)%sf(k, l, q)*dv_dx(k, l, q) - &
                                                                 q_prim_qp%vf(strxb + 1)%sf(k, l, q)*du_dx(k, l, q) + &
                                                                 q_prim_qp%vf(strxb + 2)%sf(k, l, q)*du_dy(k, l, q) + &
                                                                 q_prim_qp%vf(strxb + 1)%sf(k, l, q)*dv_dy(k, l, q) - &
                                                                 q_prim_qp%vf(strxb + 1)%sf(k, l, q)*dv_dy(k, l, q) + &
                                                                 2d0*G_K_field(k, l, q)*(1d0/2d0)*(du_dy(k, l, q) + &
                                                                                                   dv_dx(k, l, q)))

                                rhs_vf(strxb + 2)%sf(k, l, q) = rhs_vf(strxb + 2)%sf(k, l, q) + rho_K_field(k, l, q)* &
                                                                (q_prim_qp%vf(strxb + 1)%sf(k, l, q)*dv_dx(k, l, q) + &
                                                                 q_prim_qp%vf(strxb + 1)%sf(k, l, q)*dv_dx(k, l, q) - &
                                                                 q_prim_qp%vf(strxb + 2)%sf(k, l, q)*du_dx(k, l, q) + &
                                                                 q_prim_qp%vf(strxb + 2)%sf(k, l, q)*dv_dy(k, l, q) + &
                                                                 q_prim_qp%vf(strxb + 2)%sf(k, l, q)*dv_dy(k, l, q) - &
                                                                 q_prim_qp%vf(strxb + 2)%sf(k, l, q)*dv_dy(k, l, q) + &
                                                                 2d0*G_K_field(k, l, q)*(dv_dy(k, l, q) - (1d0/3d0)* &
                                                                                         (du_dx(k, l, q) + &
                                                                                          dv_dy(k, l, q))))
                            end do
                        end do
                    end do

                elseif (id == 3) then
!$acc parallel loop collapse(3) gang vector default(present)
                    do q = 0, p
                        do l = 0, n
                            do k = 0, m

                                rhs_vf(strxb)%sf(k, l, q) = rhs_vf(strxb)%sf(k, l, q) + rho_K_field(k, l, q)* &
                                                            (q_prim_qp%vf(strxb + 3)%sf(k, l, q)*du_dz(k, l, q) + &
                                                             q_prim_qp%vf(strxb + 3)%sf(k, l, q)*du_dz(k, l, q) - &
                                                             q_prim_qp%vf(strxb)%sf(k, l, q)*dw_dz(k, l, q) - &
                                                             2d0*G_K_field(k, l, q)*(1d0/3d0)*dw_dz(k, l, q))

                                rhs_vf(strxb + 1)%sf(k, l, q) = rhs_vf(strxb + 1)%sf(k, l, q) + rho_K_field(k, l, q)* &
                                                                (q_prim_qp%vf(strxb + 4)%sf(k, l, q)*du_dz(k, l, q) + &
                                                                 q_prim_qp%vf(strxb + 3)%sf(k, l, q)*dv_dz(k, l, q) - &
                                                                 q_prim_qp%vf(strxb + 1)%sf(k, l, q)*dw_dz(k, l, q))

                                rhs_vf(strxb + 2)%sf(k, l, q) = rhs_vf(strxb + 2)%sf(k, l, q) + rho_K_field(k, l, q)* &
                                                                (q_prim_qp%vf(strxb + 4)%sf(k, l, q)*dv_dz(k, l, q) + &
                                                                 q_prim_qp%vf(strxb + 4)%sf(k, l, q)*dv_dz(k, l, q) - &
                                                                 q_prim_qp%vf(strxb + 2)%sf(k, l, q)*dw_dz(k, l, q) - &
                                                                 2d0*G_K_field(k, l, q)*(1d0/3d0)*dw_dz(k, l, q))

                                rhs_vf(strxb + 3)%sf(k, l, q) = rhs_vf(strxb + 3)%sf(k, l, q) + rho_K_field(k, l, q)* &
                                                                (q_prim_qp%vf(strxb + 3)%sf(k, l, q)*du_dx(k, l, q) + &
                                                                 q_prim_qp%vf(strxb)%sf(k, l, q)*dw_dx(k, l, q) - &
                                                                 q_prim_qp%vf(strxb + 3)%sf(k, l, q)*du_dx(k, l, q) + &
                                                                 q_prim_qp%vf(strxb + 4)%sf(k, l, q)*du_dy(k, l, q) + &
                                                                 q_prim_qp%vf(strxb + 1)%sf(k, l, q)*dw_dy(k, l, q) - &
                                                                 q_prim_qp%vf(strxb + 3)%sf(k, l, q)*dv_dy(k, l, q) + &
!!                            q_prim_qp%vf(j+2)%sf(k,l,q) * dw_dz(k,l,q) + &
                                                                 q_prim_qp%vf(strxb + 5)%sf(k, l, q)*du_dz(k, l, q) + &
                                                                 q_prim_qp%vf(strxb + 3)%sf(k, l, q)*dw_dz(k, l, q) - &
                                                                 q_prim_qp%vf(strxb + 3)%sf(k, l, q)*dw_dz(k, l, q) + &
                                                                 2d0*G_K_field(k, l, q)*(1d0/2d0)*(du_dz(k, l, q) + &
                                                                                                   dw_dx(k, l, q)))

                                rhs_vf(strxb + 4)%sf(k, l, q) = rhs_vf(strxb + 4)%sf(k, l, q) + rho_K_field(k, l, q)* &
                                                                (q_prim_qp%vf(strxb + 3)%sf(k, l, q)*dv_dx(k, l, q) + &
                                                                 q_prim_qp%vf(strxb + 1)%sf(k, l, q)*dw_dx(k, l, q) - &
                                                                 q_prim_qp%vf(strxb + 4)%sf(k, l, q)*du_dx(k, l, q) + &
                                                                 q_prim_qp%vf(strxb + 4)%sf(k, l, q)*dv_dy(k, l, q) + &
                                                                 q_prim_qp%vf(strxb + 2)%sf(k, l, q)*dw_dy(k, l, q) - &
                                                                 q_prim_qp%vf(strxb + 4)%sf(k, l, q)*dv_dy(k, l, q) + &
                                                                 q_prim_qp%vf(strxb + 5)%sf(k, l, q)*dv_dz(k, l, q) + &
                                                                 q_prim_qp%vf(strxb + 4)%sf(k, l, q)*dw_dz(k, l, q) - &
                                                                 q_prim_qp%vf(strxb + 4)%sf(k, l, q)*dw_dz(k, l, q) + &
                                                                 2d0*G_K_field(k, l, q)*(1d0/2d0)*(dv_dz(k, l, q) + &
                                                                                                   dw_dy(k, l, q)))

                                rhs_vf(strxe)%sf(k, l, q) = rhs_vf(strxe)%sf(k, l, q) + rho_K_field(k, l, q)* &
                                                            (q_prim_qp%vf(strxe - 2)%sf(k, l, q)*dw_dx(k, l, q) + &
                                                             q_prim_qp%vf(strxe - 2)%sf(k, l, q)*dw_dx(k, l, q) - &
                                                             q_prim_qp%vf(strxe)%sf(k, l, q)*du_dx(k, l, q) + &
                                                             q_prim_qp%vf(strxe - 1)%sf(k, l, q)*dw_dy(k, l, q) + &
                                                             q_prim_qp%vf(strxe - 1)%sf(k, l, q)*dw_dy(k, l, q) - &
                                                             q_prim_qp%vf(strxe)%sf(k, l, q)*dv_dy(k, l, q) + &
                                                             q_prim_qp%vf(strxe)%sf(k, l, q)*dw_dz(k, l, q) + &
                                                             q_prim_qp%vf(strxe)%sf(k, l, q)*dw_dz(k, l, q) - &
                                                             q_prim_qp%vf(strxe)%sf(k, l, q)*dw_dz(k, l, q) + &
                                                             2d0*G_K_field(k, l, q)*(dw_dz(k, l, q) - (1d0/3d0)* &
                                                                                     (du_dx(k, l, q) + &
                                                                                      dv_dy(k, l, q) + &
                                                                                      dw_dz(k, l, q))))
                            end do
                        end do
                    end do
                end if
            end if
            call nvtxEndRange
```

**Comment by sbryngelson** [comment]
@js-spratt You may be thinking about these lines of code associated with the bubbles right now 

https://github.com/MFlowCode/MFC/blob/a80152ef20281ce4208016fc701795ef6910328b/src/simulation/m_rhs.f90#L1160-L1299

These are in the process of being refactored back into `m_bubbles.f90` by @anandrdbz , it was just a temporary workaround while he fixed some ACC things.

**Comment by js-spratt** [comment]
A new file ('m_hypoelastic.f90') and module (m_hypoelastic) have been added with subroutines for hypoelasticity-specific calls.

**Comment by sbryngelson** [comment]
Can someone check that all tests still pass on Summit and Expanse/Bridges2? @js-spratt @henryleberre

**Comment by henryleberre** [comment]
@sbryngelson I’ll run the tests and get back to you!

**Comment by js-spratt** [comment]
@sbryngelson @henryleberre The tests pass on Expanse CPU and GPU

**Comment by henryleberre** [comment]
@sbryngelson CPU and GPU tests pass on Summit & Bridges2.

**Pull request merged**
