### PR TITLE
goldenfile metadata generation

### PR DESCRIPTION
**Pull request by sbryngelson**
Fixes https://github.com/MFlowCode/MFC/issues/194

### CODE REVIEW

**Comment by sbryngelson** [comment]
@henryleberre requesting your review on this

**Comment by henryleberre** [comment]
@sbryngelson I made a few edits to use CMake to obtain compiler information since using environment variables can unreliable. Let me know what you think. You can try regenerating the golden files.

**Comment by sbryngelson** [comment]
@henryleberre I was thinking we would include the `pack-metadata.txt` in the repo. What do you think?

**Comment by henryleberre** [comment]
@sbryngelson I agree, we should include them. I just didn't re-generate them because I thought you would like to control how the new golden files were generated.

**Pull request merged**
