### PR TITLE
Chemistry Temperature Optimization

### PR DESCRIPTION
**Pull request by henryleberre**
## Description

- Removes the `T_idx` temperature equation. We were not solving the RHS, just using that index as temporary storage.
- Instead, adds a temperature scalar field we keep around and update. The values it holds are used as the initial guess when we solve for the temperature in the next stage.

Note: In the future, we could convert this one scalar field to a vector of scalar fields to support other features that require it. We would then define indices for each element of this array, like `T_idx = 1` for temperature if chemistry is on.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

### Scope

- [x] This PR comprises a set of related changes with a common goal

### CODE REVIEW

**Comment by sbryngelson** [comment]
Looks quite good, can you add some comments to the subroutines just in case?

**Comment by henryleberre** [comment]
Yes, will do. I am also looking into the NaNs issue…

**Comment by henryleberre** [comment]
@sbryngelson should be good to go now.

**Comment by henryleberre** [comment]
@sbryngelson rebased in the hopes the GT runners run.

**Review by sbryngelson — APPROVED** [review]

**Pull request merged**
