### PR TITLE
Add Nsight Docs

### PR DESCRIPTION
**Pull request by anshgupta1234**
This PR adds  `--nsys` and `--ncu` to the documentation. I wasn't sure how much detail to add, please let me know if there's anything important that I missed :)

### CODE REVIEW

**Comment by sbryngelson** [comment]
why did you change the CI file

**Comment by anshgupta1234** [comment]
> why did you change the CI file

My apologies, I reverted it.

**Comment by sbryngelson** [comment]
Please add links to what nsight compute and nsight sys are and their official documentation, and how to use additional flags for them. You also should describe what _they are used for_.

**Comment by anshgupta1234** [comment]
@sbryngelson Sounds good, I'll add that.

**Comment by henryleberre** [comment]
@sbryngelson @anshgupta1234 I pushed to this PR the feature that lets you specify additional arguments to `nsys` and `ncu`. For brevity, I won't explain why but it requires that `--nsys` (or `--ncu`) be specified as the last command line argument. You can just append to the invocation the arguments you want to have forwarded.

For example you could:

```console
$ ./mfc.sh run case.py [(optional) case file arguments] -N 5 -n 2 --gpu --no-mpi -j $(nproc) -t simulation -e batch .... --nsys [nsys arguments here]
```

This isn't necessarily realistic but it shows how you can use all the features together.

**Comment by sbryngelson** [comment]
@henryleberre thanks! should be useful. can you add this to the documentation as well, @anshgupta1234 ?

**Review by sbryngelson — APPROVED** [review]

**Pull request merged**
