### PR TITLE
remove adv_alphan

### LINKED ISSUE #550: `adv_alphan` is not actually used anywhere
We have `adv_alphan` as an input variable, but it was mostly taken out of the code years ago and no longer does anything. It should be removed entirely (as default _.TRUE._). For context, this feature was used only to advect $N-1$  $\alpha$ fields (so a two-component flow would only have 1 $\alpha_i$  ($i=1,1$ instead of 2 ($i=1,2$)). Then the second $\alpha_2$ would always be computed as $1-\alpha_1$ since $\sum_i \alpha_i = 1$. 

In the past, we have found it more stable to advect all the $\alpha_i$ fields separately and potentially normalize the $\alpha_i$ later to strictly enforce $\sum_i \alpha_i = 1$ via `mpp_lim` (or some other feature whose name I forget).

Thanks to @lee-hyeoksu for finding this as a dead feature.

### PR DESCRIPTION
**Pull request by lee-hyeoksu**
## Description

`adv_alphan` is not actually used in the code, so this PR removes it everywhere.

Fixes #550 

### Type of change

Please delete options that are not relevant.

- [x] Remove an obsolete parameter

### Scope

- [x] This PR comprises a set of related changes with a common goal

If you cannot check the above box, please split your PR into multiple PRs that each have a common goal.

## How Has This Been Tested?

- test suites passed on delta cpu and gpu(A100)

### CODE REVIEW

**Comment by lee-hyeoksu** [comment]
@sbryngelson`Benchmark / Georgia Tech | Phoenix (NVHPC) (gpu)` failed for an unknown reason, and `Test Suite / Self Hosted (gpu, gt)` failed to download `fftw`. Could you rerun these tests?

**Comment by sbryngelson** [comment]
Hmm. Weird. Will rerun.

**Comment by lee-hyeoksu** [comment]
Thanks. No failed test yet but two gpu tests seem not working properly..?

I don't know if they are just waiting for allocation, but I guess "!" sign seems not quite normal. Do you have any idea?

Screenshot 2024-08-01 at 12 40 54 AM

**Comment by sbryngelson** [comment]
I think it's just an issue with the runners. It should resolve. You can leave this PR alone and I will fix it, thanks @lee-hyeoksu

**Comment by lee-hyeoksu** [comment]
Benchmark failed with the following error:

```
      .=++*:          -+*+=.        | sbryngelson3@login-phoenix-rh9-1.pace.gatech.edu [Linux]
     :+   -*-        ==   =* .      | --------------------------------------------------------
   :*+      ==      ++    .+-       | 
  :*##-.....:*+   .#%+++=--+=:::.   | --jobs 1
  -=-++-======#=--**+++==+*++=::-:. | --mpi --no-gpu --no-debug --no-gcov --no-unified
 .:++=----------====+*= ==..:%..... | --targets pre_process, simulation, and post_process
  .:-=++++===--==+=-+=   +.  :=     | 
  +#=::::::::=%=. -+:    =+   *:    | ----------------------------------------------------------
 .*=-=*=..    :=+*+:      -...--    | $ ./mfc.sh (build, run, test, clean, count, packer) --help

 Comparing Benchmarks: Numbers < 1 indicate the pr/bench-cpu.yaml is faster than master/bench-cpu.yaml, > 1 indicate pr/bench-cpu.yaml is slower.
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /storage/scratch1/6/sbryngelson3/runners/actions-runner-4/_work/MFC/MFC/tool │
Terminated
│ chain/main.py:66 in <module>                                                 │
│                                                                              │
│   63 │   │                                                                   │
│   64 │   │   __print_greeting()                                              │
│   65 │   │   __checks()                                                      │
│ ❱ 66 │   │   __run()                                                         │
│   67 │                                                                       │
│   68 │   except MFCException as exc:                                         │
│   69 │   │   cons.reset()                                                    │
│                                                                              │
│ /storage/scratch1/6/sbryngelson3/runners/actions-runner-4/_work/MFC/MFC/tool │
│ chain/main.py:51 in __run                                                    │
│                                                                              │
│   48                                                                         │
│   49                                                                         │
│   50 def __run():                                                            │
│ ❱ 51 │   {"test":   test.test,     "run":        run.run,          "build":  │
│   52 │    "bench":      bench.bench,      "count":      count.count,         │
│   53 │    "packer": packer.packer, "count_diff": count.count_diff, "bench_di │
│   54 │   }[ARG("command")]()                                                 │
│                                                                              │
│ /storage/scratch1/6/sbryngelson3/runners/actions-runner-4/_work/MFC/MFC/tool │
│ chain/mfc/bench.py:135 in diff                                               │
│                                                                              │
│   132 │   │   │   │                                                          │
│   133 │   │   │   │   continue                                               │
│   134 │   │   │                                                              │
│ ❱ 135 │   │   │   if (float(f"{lhs_summary[target.name]}") <= 0.0) or math.i │
│   136 │   │   │   │   err = 1                                                │
│   137 │   │   │   │   cons.print(f"lhs_summary reports non-positive or NaN r │
│   138                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
ValueError: could not convert string to float: 'None'
 

ERROR: An unexpected exception occurred: could not convert string to float: 'None'


mfc: ERROR > main.py finished with a 143 exit code.
mfc: (venv) Exiting the Python virtual environment.
Error: Process completed with exit code 143.
```

**Comment by sbryngelson** [comment]
@lee-hyeoksu, the test suite GT Phoenix GPU run also failed (just at a different point). I will fix this since it should be simple (I think). 

The benchmarking failure probably won't be fixed with a rerun. It looks like one of the benchmark cases failed entirely, perhaps all of them. You could download the artifacts of the benchmark run and see where it failed specifically. Basically the error you point out says that one of the benchmark simulations did not actually run.

**Comment by sbryngelson** [comment]
This is a good PR for fixing the runners because I'm pretty confident that it should pass everything (no major code changes).

**Comment by lee-hyeoksu** [comment]
> You could download the artifacts of the benchmark

It would be great. Where can I download them?

**Pull request merged**
