### PR TITLE
Upstream fixes from henryleberre/[amdgpu, gcc-acc] and other things

### LINKED ISSUE #171: Docker container migration
The Docker container and fetching it need to either be removed or updated so that it's synced with an agnostic Docker account (rather than @henryleberre 's personal account). 

It hasn't been updated in several months. I'm not using Windows, so I'm not sure if this last part matters.

### PR DESCRIPTION
**Pull request by henryleberre**
This PR aims to upstream non-experimental changes made in my `amdgpu` and `gcc-acc` branches, including:
- CMake on CCE: Fixed argument splitting (and combining) with the `SHELL:` prefix.
- Fypp Macros: Improved logging (stdout flushing).
- `mfc.sh load`: Bumped CCE version for Crusher & created `toolchain/modules`.
- `gnu_acc.sh`: A script that automates the process of building an offloading GNU compiler on the correct development branch with support for NVIDIA and AMD targets.
- Refactored parts of `mfc.sh test` and add the `--add-new-variables` (see documentation).
- Refactored the CI workflows (expanded scope & simplified .yml).
- Docker: Rewrote the Dockerfile to use an Ubuntu base image and updated the publishing workflow to fix #171.
- Updated the documentation website's theme to look nicer (see the new version [here](https://henryleberre.github.io/MFC-DOC.github.io/documentation/md_getting-started.html))
- Testing without MPI installed is now supported (`—-no-mpi`). There was a bug that required that an MPI binary (e.g. mpirun/srun/…) be present.
- Commented CMakeLists.txt.
- Refactored how the documentation is generated in CMakeLists.txt.
- Refactored testing to only use one case file. iT is included in source control along with a README.
- Fixed a bug in calls to Silo's `DBPUTCURVE` where the datatype argument was specified incorrectly.
- Some miscellaneous improvements.

### CODE REVIEW

**Comment by henryleberre** [comment]
@sbryngelson Phoenix' queue appears to have been full:

Screenshot 2023-06-08 at 1 04 02 PM

**Comment by sbryngelson** [comment]
I'm on it

**Comment by henryleberre** [comment]
@sbryngelson Once you create the Docker Hub account, I can update the `mfc.sh` file to pull from that account.

**Comment by sbryngelson** [comment]
Found a problem with the website update here: https://henryleberre.github.io/MFC-DOC.github.io/documentation/md_case.html syntax problem with `<tt>`

**Comment by sbryngelson** [comment]
The problem with your Phoenix CI is that you are loading different modules in `Build` and `Test`. In build it looks like you changed the command a bit, and it's also using GNU compilers. In the SLURM files in `/misc` you will see the problem https://github.com/MFlowCode/MFC/blob/master/misc/run-phoenix-release-cpu.sh 

https://github.com/MFlowCode/MFC/blob/5e7fc2a3278adcd33bdd9fb445ef51789d51fb5c/misc/run-phoenix-release-cpu.sh#L1-L14

https://github.com/MFlowCode/MFC/blob/5e7fc2a3278adcd33bdd9fb445ef51789d51fb5c/misc/run-phoenix-release-gpu.sh#L1-L14

They load the same modules for CPU and GPU on Phoenix, then runs one case on CPUs and another on GPUs (via different CIs).

**Comment by henryleberre** [comment]
@sbryngelson Thanks, that explains the error for the CPU case. I think my last push should fix the GPU issue. For the documentation problem, it actually is already visible on the regular MFC website (https://mflowcode.github.io/documentation/md_case.html). It doesn't seem critical so I might take a look at this later (we _may_ have to file an issue with Doxygen).

**Comment by sbryngelson** [comment]
> @sbryngelson Thanks, that explains the error for the CPU case. I think my last push should fix the GPU issue. For the documentation problem, it actually is already visible on the regular MFC website ([mflowcode.github.io/documentation/md_case.html](https://mflowcode.github.io/documentation/md_case.html)). It doesn't seem critical so I might take a look at this later (we _may_ have to file an issue with Doxygen).

FYI for the Doxygen I would accept just getting rid of that part of the subsection title for now. I think it doesn't warrant trying to _fix_ Doxygen and instead we can just rephrase the title so it doesn't need `<tt>`

**Comment by henryleberre** [comment]
@sbryngelson After some extensive Git trickery and debugging, this PR should be ready now.

**Comment by sbryngelson** [comment]
@henryleberre thanks, this is perfect! (aside from the fact that it seems to have broken some tests?)

**Comment by henryleberre** [comment]
@sbryngelson Turns out it was a spurious error with GT Phoenix. I reran the job and it passed!

**Comment by sbryngelson** [comment]
@henryleberre this latest commit has failed macos mpi no-debug testing a few times now.

**Pull request merged**
