### PR TITLE
Delta module update

### PR DESCRIPTION
**Pull request by mrodrig6**
## Description

Updated the Delta modules in the MFC toolchain.

The updated modules pass the test suite.

### Type of change

- [x ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Pass full test suite. 

* What computers and compilers did you use to test this: ACCESS DELTA

### CODE REVIEW

**Comment by sbryngelson** [comment]
So can we get rid of the `LD_LIBRARY_PATH` extension in the Mako template?

**Review by sbryngelson — CHANGES_REQUESTED** [review]
Needs attention to the `delta.mako` template file.

**Comment by sbryngelson** [comment]
Something else about this also doesn't quite make sense, it seems like you want a different cuda and mpi:
```console
dt-login02: bryngel/MFC $ module load python/3.11.6 nvhpc/24.1 openmpi/4.1.5+cuda cmake

Lmod is automatically replacing "gcc/11.4.0" with "nvhpc/24.1".


The following have been reloaded with a version change:
  1) cuda/11.8.0 => cuda/12.3.0     2) openmpi/4.1.6 => openmpi/4.1.5+cuda

dt-login02: bryngel/MFC $ module list

Currently Loaded Modules:
  1) cue-login-env/1.0   4) python/3.11.6       7) cuda/12.3.0
  2) slurm-env/0.1       5) gcc-runtime/8.5.0   8) openmpi/4.1.5+cuda
  3) default-s11         6) nvhpc/24.1          9) cmake/3.27.9
```

**Comment by wilfonba** [comment]
Completed in #643

**Pull request closed without merging**
