### PR TITLE
Handshake: Benchmarking

### PR DESCRIPTION
**Pull request by henryleberre**

### CODE REVIEW

**Comment by sbryngelson** [comment]
I noticed that the outputs of the regular test suite Phoenix runners are sent to artifacts. This makes it hard to quickly find the problem (though it is probably more elegant in some other ways). Can we revert back to something that shows the stdout/err to the developer in the actions call stack? My old way of `cat test.out` was a bit hacky but worked, not sure if there is a nicer way.

**Comment by henryleberre** [comment]
@sbryngelson I added that feature back and removed `3D_sphbubcollapse` from the list of benchmarked cases. This should be a (not-so minimal) MVP for the Benchmarking feature. It can be expanded upon in the future.

**Comment by sbryngelson** [comment]
@henryleberre Phoenix is undergoing maintenance for the next few days so I suppose this will sit for this week.

**Comment by sbryngelson** [comment]
closes https://github.com/MFlowCode/MFC/issues/225

**Comment by sbryngelson** [comment]
closes https://github.com/MFlowCode/MFC/issues/49

**Review by sbryngelson — APPROVED** [review]

**Comment by sbryngelson** [comment]
closes https://github.com/MFlowCode/MFC/pull/316#pullrequestreview-1839029903

**Comment by sbryngelson** [comment]
did it just fail because of this?  `cat: .github/workflows/phoenix/bench.sh: No such file or directory`

**Pull request merged**
