### PR TITLE
Documentation typos

### PR DESCRIPTION
**Pull request by ChrisZYJ**
## Description

All `%`'s are missing on the Case Files page. Fixed by replacing `%` within literal backtick expressions by `%%`. Also fixed some other typos / formatting. 

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### Scope

- [x] This PR comprises a set of related changes with a common goal

### CODE REVIEW

**Comment by sbryngelson** [comment]
Thanks @ChrisZYJ! It took me way to long to figure this out, but the solution is to use two percent signs to get one real one. x%%y in a literal backtick expression = `x%y` on the website

**Comment by ChrisZYJ** [comment]
Thanks! I would never have thought of that on my own

**Comment by sbryngelson** [comment]
> Thanks! I would never have thought of that on my own

Me either! Some careful Googling found the trick for me. You can build the documentation on your local machine via `./mfc.sh build -t documentation` to try many different things or just check things are working as expected.

**Review by sbryngelson — APPROVED** [review]

**Comment by ChrisZYJ** [comment]
Thanks for the tips on how to build the pages locally - that makes debugging much easier. 

Just found a few more issues: while `a%%b` -> `a%b` works, `a%%b[x]` -> `a%%b[x]` introduces an extra `%` instead. Same for `a%%` -> `a%%`. Fixing that now

**Pull request merged**
