### PR TITLE
Fix 3D IBM Infinite CFL Number on GPUs

### PR DESCRIPTION
**Pull request by Sam-Briney**
## Description

Fixes 3D IBM infinite CFL number when running on GPUs. These modifications were suggested by @haochey and @anandrdbz via slack

### Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### Scope

- [x] This PR comprises a set of related changes with a common goal

## How Has This Been Tested?

- [x] Tested by running the 3D_ibm example on two A100 GPUs
visit0000

**Test Configuration**:

* What computers and compilers did you use to test this:

The test was run using Nvidia A100 GPUs on HiPerGator at UF
`python/3.8, nvhpc/24.5, openmpi/4.1.6, cmake/3.26.4`

## Checklist
- [x] I ran ```./mfc.sh format``` before committing my code
- [x] This PR does not introduce any repeated code (it follows the [DRY])
- [x] I cannot think of a way to condense this code and reduce any introduced additional line count

### If your code changes any code source files (anything in `src/simulation`)

To make sure the code is performing as expected on GPU devices, I have:
- [x] Checked that the code compiles using NVHPC compilers

### CODE REVIEW

**Comment by sbryngelson** [comment]
I'm confused by the removal of these:

```fortran
        if (ib .and. t_step == 1) then
            if (qbmm .and. .not. polytropic) then
                call s_ibm_correct_state(q_cons_ts(1)%vf, q_prim_vf, pb_ts(1)%sf, mv_ts(1)%sf)
            else
                call s_ibm_correct_state(q_cons_ts(1)%vf, q_prim_vf)
            end if
        end if
```

If you remove all of these then the whole subroutine `s_ibm_correct_state` can be removed because these are the only places it gets called. What exactly is the purpose of this routine (or removing it?) @anandrdbz @Sam-Briney

**Comment by Sam-Briney** [comment]
@sbryngelson I think it gets called in a few other places as well. For example: https://github.com/MFlowCode/MFC/blob/78fd0c51735f1c514d6b804531278b6dd3a3ef8f/src/simulation/m_time_steppers.fpp#L690

I believe it was getting called twice instead of just once at the first time step.

**Comment by sbryngelson** [comment]
Ah I see, you're correct @Sam-Briney. Does this fix the issue with the visualization inside the IBM being incorrect on >1 GPU?

**Comment by Sam-Briney** [comment]
@sbryngelson It does not fix the visualization issue. I thought it might be better to make a more focused PR to make this functionality available in the short term

**Review by sbryngelson — APPROVED** [review]

**Comment by sbryngelson** [comment]
Makes sense. Merging.

**Pull request merged**
