### PR TITLE
Upstream non-Phase Change additions from #179

### PR DESCRIPTION
**Pull request by henryleberre**
Upstream non-Phase Change additions from #179.

### CODE REVIEW

**Comment by sbryngelson** [comment]
thanks for doing this @henryleberre -- this will be convenient.

**Comment by sbryngelson** [comment]
@henryleberre, I need clarification on part of this PR. You added the test cases corresponding to phase change, but the phase change feature has not been added to MFC yet (the PR is still awaiting revision). Is this intentional? It seems more natural to add those test cases when the phase change features are added.

**Comment by henryleberre** [comment]
This is the case some overzealous `grep`'ing on my end - let me fix that now!

**Comment by henryleberre** [comment]
@sbryngelson I removed the phase-change tests.

**Comment by sbryngelson** [comment]
@henryleberre they still appear to be there? There are also diffs to non-phase-change test case goldenfiles that seem erroneous.

**Comment by henryleberre** [comment]
@sbryngelson, apologies.. I have no idea what happened there. I just ran - again:
```console
~/MFC-JRChreim $ git reset --soft HEAD~1
~/MFC-JRChreim $ git restore --staged $(git status | grep README | awk '{print $3}' | sed s/README\.md//g | tr '\n' ' ')
~/MFC-JRChreim $ git commit -m 'Internal energy calculation bugfix' --author="JRChreim <jrchreim@outlook.com>"
```

The tests whose golden files were modified are these:
```console
~/MFC-JRChreim $ ./mfc.sh test -l | grep 'model_eqns=3'
  2F35A1FE   1D -> 1 Fluid(s) -> riemann_solver=2 -> model_eqns=3
  FD891191   1D -> 2 Fluid(s) -> riemann_solver=2 -> model_eqns=3
  043B535A   2D -> 1 Fluid(s) -> riemann_solver=2 -> model_eqns=3
  4F2F4ACE   2D -> 2 Fluid(s) -> riemann_solver=2 -> model_eqns=3
  B89B8C70   2D -> Axisymmetric -> model_eqns=3
  6241177B   3D -> 1 Fluid(s) -> riemann_solver=2 -> model_eqns=3
  F0E6771E   3D -> 2 Fluid(s) -> riemann_solver=2 -> model_eqns=3
```

These were meant to be updated by @JRChreim, fixing the internal energy calculation for `model_eqns=3`.

**Review by sbryngelson — APPROVED** [review]

**Pull request merged**
