### PR TITLE
Fixed a bug on pi_inf and enabled subgrid bubble model for viscous flow

### PR DESCRIPTION
**Pull request by lee-hyeoksu**
1. Fixed a bug that the capital 'pi_inf' was used where the little 'pi_inf' should be used. Also, computing speed of sound is also corrected.

2. Enabled subgrid bubble model for viscous flow
    - Added codes that computes the Reynolds number properly when 'bubbles=T'

3. Modified codes to make 'vel_profile' and 'instability_wave' options compatible with 'bubbles=T' and 'num_fluids=1'

4. Changed grid numbers in example/3D_turb_mixing to prevent memory issue (#149)

### CODE REVIEW

**Comment by anandrdbz** [comment]
These changes seem fine, you might wanna change the definition of B_tait in m_qbmm as well. Other than that everything looks fine. The tests won't pass as of now due to this change as the golden files need to be regenerated for this definition of pi-inf

**Comment by lee-hyeoksu** [comment]
Thanks @anandrdbz and @sbryngelson. The definition of `B_tait` in m_qbmm is now changed, and the golden files for the cases with sub-grid bubbles are updated.

**Comment by sbryngelson** [comment]
@lee-hyeoksu your PR is failing GPU tests on the bubble cases I think.

**Comment by lee-hyeoksu** [comment]
@sbryngelson The failure on GPU was because I didn't add `Re_L` and `Re_R` to the private clause for OpenACC when I added codes for computing `Re_L` and `Re_R` in `m_riemann_solvers`. Now it is fixed.

**Comment by sbryngelson** [comment]
Great, thanks @lee-hyeoksu ! Can you also add _new_ tests for the case of viscous effects + subgrid bubbles? So we can track if code associated with those effects changes or breaks. Again, there should be some documentation on this (adding new tests).

**Comment by lee-hyeoksu** [comment]
@sbryngelson I added new tests, and they appear in the list by `./mfc.sh test -l`. But is there anywhere I should add documentation?

**Review by sbryngelson — APPROVED** [review]

**Pull request merged**
