### PR TITLE
Syscheck: Run a system check before running MFC & More

### PR DESCRIPTION
**Pull request by henryleberre**
- Add a System Check Utility
- Add the capability to run a certain % of test cases (e.g. `mfc.sh test -% 50`) - Used by Debug runs to lower runtime.
- Let the test suite use multiple GPUs with IDs specified through the command line (effective load balancing).

The GPU CI that runs on Phoenix now does this:

```console
$ ./mfc.sh test -a -b mpirun -j $(nproc) \
                --gpu -g $(seq -s ',' 0 $(($(nvidia-smi -L | wc -l)-1)))
```

### CODE REVIEW

**Comment by sbryngelson** [comment]
Hmm is `./mfc.sh test` executing the syscheck executable?

e.g., it doesn't look like it here: https://github.com/MFlowCode/MFC/actions/runs/5702453509/job/15454159748?pr=198#step:8:62

**Comment by henryleberre** [comment]
@sbryngelson `mfc.sh test` calls `mfc.sh run` which does run `syscheck`.

**Comment by sbryngelson** [comment]
I believe it and I think I see the logic in the toolchain but it seems useful to have it print that the `syscheck` was successful (or something like that). It should make it more clear when it _isn't_ successful.

**Comment by henryleberre** [comment]
It isn't displayed while testing for the reason I described but if it isn't successful, it will abort. Here is what is displayed when you run a case:
```console
XPS: CPG/MFC $ r examples/1D_bubblescreen/case.py -t pre_process
mfc: OK > (venv) Entered the Python virtual environment.
...
Run
  Acquiring /home/henryleberre/CPG/MFC/examples/1D_bubblescreen/case.py...
  Configuration:
    Input               /home/henryleberre/CPG/MFC/examples/1D_bubblescreen/case.py
    Job Name      (-#)  MFC
    Engine        (-e)  interactive
    Nodes         (-N)  1
    Tasks (/node) (-n)  1
    MPI Binary    (-b)  mpirun
  Generating input files for pre_process...

    Generating pre_process.inp.
      INFO: Forwarded 63/92 parameters.

    Generating pre_process/include/case.fpp.
      INFO: Existing case.fpp file is up to date.

  Building pre_process:

    $ cmake --build /home/henryleberre/CPG/MFC/build/pre_process --target pre_process -j 20 --config Release

[0/2] Re-checking globbed directories...
ninja: no work to do.

    $ cmake --install /home/henryleberre/CPG/MFC/build/pre_process

-- Install configuration: "Release"
-- Up-to-date: /home/henryleberre/CPG/MFC/build/install/bin/pre_process

  Building syscheck:

    $ cmake --build /home/henryleberre/CPG/MFC/build/syscheck --target syscheck -j 20 --config Release

[0/2] Re-checking globbed directories...
ninja: no work to do.

    $ cmake --install /home/henryleberre/CPG/MFC/build/syscheck

-- Install configuration: "Release"
-- Up-to-date: /home/henryleberre/CPG/MFC/build/install/bin/syscheck

  Ensuring the Interactive Engine works (30s timeout) via syscheck:


    $ mpirun -np 1 /home/henryleberre/CPG/MFC/build/install/bin/syscheck

 [TEST] MPI: call mpi_init(ierr)
 [TEST] MPI: call mpi_comm_rank(MPI_COMM_WORLD, rank, ierr)
 [TEST] MPI: call mpi_barrier(MPI_COMM_WORLD, ierr)
 [TEST] MPI: call assert(rank >= 0)
 [TEST] MPI: call mpi_comm_size(MPI_COMM_WORLD, nRanks, ierr)
 [TEST] MPI: call assert(nRanks > 0 .and. rank < nRanks)
 [SKIP] ACC: devtype = acc_get_device_type()
 [SKIP] ACC: num_devices = acc_get_num_devices(devtype)
 [SKIP] ACC: call assert(num_devices > 0)
 [SKIP] ACC: call acc_set_device_num(mod(rank, nRanks), devtype)
 [SKIP] ACC: allocate(arr(1:N))
 [SKIP] ACC: !$acc enter data create(arr(1:N))
 [SKIP] ACC: !$acc parallel loop
 [SKIP] ACC: !$acc update host(arr(1:N))
 [SKIP] ACC: !$acc exit data delete(arr)
 [TEST] MPI: call mpi_barrier(MPI_COMM_WORLD, ierr)
 [TEST] MPI: call mpi_finalize(ierr)

 Syscheck: PASSED.

  Running pre_process:

    $ mpirun -np 1 /home/henryleberre/CPG/MFC/build/install/bin/pre_process

 Pre-processing a 100x0x0 case on 1 rank(s)
 Processing patch           1
 Processing patch           2
 In convert, nbub:   2.3873241463784300E-013
 Final Time   4.4309999999999974E-003

    Done (in 0:00:00.465880)
mfc: (venv) Exiting the Python virtual environment.
```

We show the invocation of `syscheck` but I wonder if the we should keep the entire output. Here is what happens if it fails (I added `stop 1`):

```console
XPS: CPG/MFC $ r examples/1D_bubblescreen/case.py -t pre_process
mfc: OK > (venv) Entered the Python virtual environment.
...
Run
  Acquiring /home/henryleberre/CPG/MFC/examples/1D_bubblescreen/case.py...
  Configuration:
    Input               /home/henryleberre/CPG/MFC/examples/1D_bubblescreen/case.py
    Job Name      (-#)  MFC
    Engine        (-e)  interactive
    Nodes         (-N)  1
    Tasks (/node) (-n)  1
    MPI Binary    (-b)  mpirun
  Generating input files for pre_process...

    Generating pre_process.inp.
      INFO: Forwarded 63/92 parameters.

    Generating pre_process/include/case.fpp.
      INFO: Existing case.fpp file is up to date.

  Building syscheck:

    $ cmake --build /home/henryleberre/CPG/MFC/build/syscheck --target syscheck -j 20 --config Release

[0/2] Re-checking globbed directories...
[5/5] Linking Fortran executable syscheck

    $ cmake --install /home/henryleberre/CPG/MFC/build/syscheck

-- Install configuration: "Release"
-- Installing: /home/henryleberre/CPG/MFC/build/install/bin/syscheck

  Building pre_process:

    $ cmake --build /home/henryleberre/CPG/MFC/build/pre_process --target pre_process -j 20 --config Release

[0/2] Re-checking globbed directories...
ninja: no work to do.

    $ cmake --install /home/henryleberre/CPG/MFC/build/pre_process

-- Install configuration: "Release"
-- Up-to-date: /home/henryleberre/CPG/MFC/build/install/bin/pre_process

  Ensuring the Interactive Engine works (30s timeout) via syscheck:


    $ mpirun -np 1 /home/henryleberre/CPG/MFC/build/install/bin/syscheck

 [TEST] MPI: stop 1
STOP 1
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[1249,1],0]
  Exit code:    1
--------------------------------------------------------------------------


Error: The Interactive Engine appears to hang or exit with a non-zero status code. This may indicate that the wrong MPI binary is being used to launch parallel jobs. You can
specify the correct one for your system using the <-b,--binary> option. For example:
 - ./mfc.sh run <myfile.py> -b mpirun
 - ./mfc.sh run <myfile.py> -b srun
Reason: Exit code.
```

I forgot to update the error message here.

**Comment by sbryngelson** [comment]
That's perfect, thanks.

**Review by sbryngelson — APPROVED** [review]

**Comment by sbryngelson** [comment]
@henryleberre check this out: https://github.com/MFlowCode/MFC/actions/runs/5702453509/job/15454159326?pr=198

It looks like we are soon going to be regularly running afoul of the GitHub 6hr runner limit on debug runs. All of the time is associated with running (not building). T

I'm wondering what debug options we are using that are exploding runtime so flagrantly, and if they're truly useful or not:
* If there are debug options doing this that aren't very useful, we can remove them in good conscience. 
* If they are all quite useful and about equally contributing to runtime, then we may need to peel back the test suite for debug runs. Perhaps it only runs half of the 3D tests, or maybe only a couple of them.

Similarly, I'm wondering what we can do to make the runtime for some of these runners less excessive. For example, it takes Phoenix > 1hr to run CPU non-debug tests. This doesn't seem right (and the silly ol' GH runners manage the same in 30min). It also takes Phoenix 38 minutes to build MFC GPU release. Does it take that long on an actual login or compute node?

**Comment by sbryngelson** [comment]
This is ready for squash + merge @henryleberre

**Comment by henryleberre** [comment]
@sbryngelson Do you think these commits should be squashed?

**Comment by sbryngelson** [comment]
I'm fine with either.

**Pull request merged**
